//! `pico8` -- the shared PICO-8 runtime for PlayStation 1 ports.
//!
//! This crate holds everything that is the same across PICO-8 games:
//!
//! - [`fixed`]: PICO-8's 16.16 fixed-point (`Fix32`), bit-exact mul/div/mod/
//!   floor/sin/cos.
//! - [`rng`]: PICO-8's LCG (`srand`/`rnd`/`random`), bit-exact.
//! - [`backend`]: PICO-8's draw/query API (`spr`/`map`/`rectfill`/`line`/
//!   `circfill`/`print`/`pal`/`camera`/`mget`/`fget`) on the PSoXide GPU,
//!   parameterised over a [`backend::Cart`] (the game's spritesheet + map).
//! - [`sfx`]: PICO-8's `sfx`/`music` on the PSoXide SPU, parameterised over
//!   the game's [`sfx::AudioData`].
//! - [`palette`] / [`font`]: the universal PICO-8 16-colour CLUT and font.
//!
//! A game crate supplies its own `assets` (gfx/tilemap/audio, generated by
//! `tools/p8_to_rust.py`) and game logic, calls [`backend::set_cart`] +
//! [`sfx::init`] once, and then drives [`backend`] from its update/draw loop.

#![no_std]
#![allow(static_mut_refs)]

pub mod backend;
pub mod fixed;
pub mod font;
pub mod palette;
pub mod rng;
pub mod sfx;
mod sin_table;
