#!/usr/bin/env python3
"""Resample CC0 menu SFX (Kenney "Interface Sounds", public domain) to 22050 Hz
mono and encode each as a one-shot PS1 SPU ADPCM sample. Emits a Rust asset."""
import sys, os, subprocess, struct
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
import adpcm

SRC = "/tmp/kenney_sfx/kenney-interface-sounds-master/addons/kenney_interface_sounds"
RATE = 22050
# (const name, source wav)  -- order defines the index
SOUNDS = [
    ("SFX_NAV",        "select_001.wav"),       # cursor move
    ("SFX_CONFIRM",    "confirmation_001.wav"),  # launch / pause confirm
    ("SFX_TRANSITION", "maximize_001.wav"),      # intro -> menu reveal
]

def load_pcm(path):
    raw = subprocess.run(
        ["ffmpeg","-v","error","-i",path,"-ac","1","-ar",str(RATE),"-f","s16le","-"],
        capture_output=True).stdout
    return list(struct.unpack("<%dh" % (len(raw)//2), raw))

def trim_norm(s):
    # trim trailing near-silence, normalise peak to ~0.85
    thr = 200
    end = len(s)
    while end > 1 and abs(s[end-1]) < thr:
        end -= 1
    s = s[:end]
    peak = max(1, max(abs(v) for v in s))
    g = int(0.85 * 32767) / peak
    return [max(-32768, min(32767, int(v*g))) for v in s]

def encode_oneshot(s16):
    pad = (-len(s16)) % 28
    s = list(s16) + [0]*pad
    nb = len(s)//28
    out, p1, p2 = [], 0, 0
    for b in range(nb):
        flags = 0x01 if b == nb-1 else 0x00   # last block: loop-end, no repeat -> mute
        blk, p1, p2 = adpcm._encode_block(s[b*28:(b+1)*28], p1, p2, flags)
        out += blk
    return bytes(out)

blobs, table, names = [], [], []
off = 0
for name, wav in SOUNDS:
    pcm = trim_norm(load_pcm(os.path.join(SRC, wav)))
    adp = encode_oneshot(pcm)
    blobs.append(adp)
    table.append((off, len(pcm)))
    names.append(name)
    print(f"{name:16s} {wav:22s} {len(pcm):5d} smp -> {len(adp):5d} B adpcm @ 0x{off:04x}")
    off += len(adp)

data = b"".join(blobs)
out = ["// Auto-generated by tools/gen_menu_sfx.py. Do not edit by hand.",
       "// Source: Kenney \"Interface Sounds\" (CC0 / public domain). 22050 Hz mono,",
       "// one-shot PS1 SPU ADPCM (last block flag 0x01 = end, no loop).", ""]
out.append(f"pub static MENU_SFX_ADPCM: [u8; {len(data)}] = [")
for i in range(0, len(data), 16):
    out.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+16]) + ",")
out.append("];\n")
out.append("/// (byte offset into MENU_SFX_ADPCM, sample count) per sound.")
out.append(f"pub static MENU_SFX: [(u32, u32); {len(table)}] = [")
for (o, n) in table:
    out.append(f"    ({o}, {n}),")
out.append("];\n")
for i, nm in enumerate(names):
    out.append(f"pub const {nm}: usize = {i};")
out.append("")
open("shared/src/menu_sfx_data.rs","w").write("\n".join(out))
print("wrote shared/src/menu_sfx_data.rs  (", len(data), "bytes adpcm )")
