#!/usr/bin/env python3
"""Build the PlayStation button-icon atlas (15bpp) from a high-res source sheet.

Crops the four icons we use (Triangle, Circle, Start = play, Select = oblong) out
of the ChatGPT-generated sheet, downscales them to PS1 hint size, composites their
anti-aliased edges over black (both the menu and the pause sit on dark
backgrounds), keys the light checkerboard background out to PS1's transparent
texel (0x0000), and packs them into a 64-wide 15bpp atlas.

Emits shared/src/icons_data.rs: ATLAS (raw u16 BGR555, 0x0000 = transparent) plus
the (u, v, w, h) cell of each icon. Drawn via pico8::icons (textured quads).
"""
import numpy as np
from PIL import Image

SRC = "/Users/ebonura/Downloads/ChatGPT Image Jun 17, 2026, 05_14_19 PM.png"
OUT = "/Users/ebonura/Desktop/repos/pico8-psx/shared/src/icons_data.rs"
ATLAS_W = 64
H = 14  # icon height in screen px

# source bounding boxes (x0, y0, x1, y1) + crop padding
CROPS = {
    "triangle": (92, 130, 285, 327, 6),
    "circle":   (384, 130, 578, 327, 6),
    "cross":    (675, 130, 869, 327, 6),
    "start":    (366, 709, 515, 851, 14),
    "select":   (714, 746, 879, 830, 16),
}

src = Image.open(SRC).convert("RGB")


def boost(rgb):
    """Make the icons feel alive: lift saturation and brightness."""
    luma = rgb @ np.array([0.299, 0.587, 0.114])
    rgb = luma[..., None] + (rgb - luma[..., None]) * 1.7  # saturation
    rgb = rgb * 1.45 + 12  # brightness / gain
    return np.clip(rgb, 0, 255)


def prep(box):
    x0, y0, x1, y1, pad = box
    c = src.crop((x0 - pad, y0 - pad, x1 + pad, y1 + pad))
    h = H
    w = round(c.width * h / c.height)
    c = c.resize((w, h), Image.LANCZOS)
    a = np.array(c).astype(float)
    bright = a.sum(2) / 3
    alpha = np.clip((215 - bright) / 175, 0, 1)  # 0 on light bg, 1 on dark icon
    rgb = boost(a * alpha[:, :, None])  # composite over black, then liven up
    return rgb.astype(int), alpha, w, h


def to_bgr555(r, g, b, opaque):
    if not opaque:
        return 0
    r5, g5, b5 = r >> 3, g >> 3, b >> 3
    return 0x8000 | (b5 << 10) | (g5 << 5) | r5  # mask bit set -> opaque


# pack into rows, 64 wide
cells = {}
atlas_rows = []  # list of (list-of-(name,rgb,alpha,w,h)) packed per row
cur, curw = [], 0
order = ["triangle", "circle", "cross", "start", "select"]
prepared = {k: prep(CROPS[k]) for k in order}
for k in order:
    rgb, alpha, w, h = prepared[k]
    if curw + w + 1 > ATLAS_W:
        atlas_rows.append(cur)
        cur, curw = [], 0
    cur.append((k, rgb, alpha, w, h))
    curw += w + 1
if cur:
    atlas_rows.append(cur)

atlas_h = sum(max(c[4] for c in row) for row in atlas_rows) + len(atlas_rows)
atlas = np.zeros((atlas_h, ATLAS_W), dtype=np.uint16)
y = 0
for row in atlas_rows:
    x = 0
    rowh = max(c[4] for c in row)
    for name, rgb, alpha, w, h in row:
        for yy in range(h):
            for xx in range(w):
                r, g, b = rgb[yy, xx]
                atlas[y + yy, x + xx] = to_bgr555(r, g, b, alpha[yy, xx] > 0.35)
        cells[name] = (x, y, w, h)
        x += w + 1
    y += rowh + 1

flat = atlas.flatten()
with open(OUT, "w") as f:
    f.write("// @generated by tools/gen_icons.py -- PlayStation button icon atlas.\n")
    f.write("// 15bpp BGR555 (0x0000 = transparent), uploaded at VRAM (576, 0).\n\n")
    f.write(f"pub const ATLAS_W: i16 = {ATLAS_W};\n")
    f.write(f"pub const ATLAS_H: i16 = {atlas_h};\n\n")
    f.write("/// (u, v, w, h) cell within the atlas.\n")
    f.write("pub struct Cell { pub u: u8, pub v: u8, pub w: u8, pub h: u8 }\n\n")
    for name in order:
        u, v, w, h = cells[name]
        f.write(f"pub const {name.upper()}: Cell = Cell {{ u: {u}, v: {v}, w: {w}, h: {h} }};\n")
    f.write(f"\npub const ATLAS: [u16; {len(flat)}] = [\n")
    for i in range(0, len(flat), 16):
        f.write("    " + ", ".join(f"0x{v:04x}" for v in flat[i:i + 16]) + ",\n")
    f.write("];\n")

print(f"atlas {ATLAS_W}x{atlas_h}, cells: {cells}")
print(f"wrote {OUT}")
